myapp/urls.py
from django.urls import path
from myapp import views

app_name="myapp"

urlpatterns = [
    path('courses', views.courses, name="courses"),
    path('about', views.about, name="about"),
    path('contact', views.contact, name="contact"),
    path('signup', views.signup, name="signup"),
    path('check_user', views.check_user, name="check_user"),
    path('user_login', views.user_login, name="user_login"),
    path('dashboard', views.dashboard, name="instructor_dashboard"),
    path('instructor_profile', views.instructor_profile, name="instructor_profile"),
    path('us_logout', views.us_logout, name="us_logout"),
    path('inst_add_course', views.inst_add_course, name="inst_add_course"),
    path('instructor_courses', views.instructor_courses, name="instructor_courses"),
    path('edit_course', views.edit_course, name="edit_course"),
    path('delete_topic', views.delete_topic, name="delete_topic"),
    path('add_inst_experience', views.add_inst_experience, name="add_inst_experience"),
    path("change_pass",views.change_pass,name="change_pass"),
    path("single_course",views.single_course,name="single_course"),
    path("get_course_data",views.get_course_data,name="get_course_data"),
    path("cart",views.add_cart,name="cart"),
    path("process_payment",views.process_payment,name="process_payment"),
    path("student_orders",views.student_orders,name="student_orders"),
    path("pending_orders",views.pending_orders,name="pending_orders"),
    path("remove_cart",views.remove_cart,name="remove_cart"),
    path("forgot_pass",views.forgot_pass,name="forgot_pass"),
    path("verify_otp",views.verify_otp,name="verify_otp"),
    path("student_single_course",views.student_single_course,name="student_single_course"),
    path("my_students",views.my_students,name="my_students"),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path("myapp/",include("myapp.urls")),

    path('paypal/', include('paypal.standard.ipn.urls')),

    path('ps/',views.p_success,name='ps'),
    path('pf/',views.p_fail, name='pf' ),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/cart.html
{% extends "base.html" %}
{% block content %}
<style>
        tr .title{
                width: 50%;
        }
        input[type="image"]{
                height:50px;
        }
</style>
{% if not user.is_authenticated %}
<div style="height:100px;background:#6610f2;"></div>
        <div class="container">
                <div class="row">
                        <div class=" col-md-12 jumbotron my-4">
                                <h1>YOU NEED TO LOGIN FIRST</h1>
                        </div>
                </div>
        </div>
{% else %}
<!-- bradcam_area_start -->
        <div class="bradcam_area overlay2" style="background:url('/static/cart.jpg');background-size:100% 100%;">
                <h3>My Cart ({{items|length}}) </h3>
        </div>
            <!-- bradcam_area_end -->
    <!-- ================ contact section start ================= -->
    <section class="contact-section">
        <div class="container-fluid">
                <div class="row">
                        <div class="col-md-12">
                                {% if status %}
                                        <div class="alert {{class}}">{{status}}</div>
                                {% endif %}
                        </div>
                </div>
                <div class="row" id="mycart">
                        <div class="col-md-8">
                                <table class="table table-hover">
                                        <tbody>
                                                {% for i in items %}
                                                <tr>
                                                        <td>
                                                                <a href="single_course?cid={{i.course_id.id}}&type=normal">
                                                                <img src="/media/{{i.course_id.cover_image}}" style="width:100px;height:80px;">
                                                                </a>
                                                        </td>
                                                        <td class="title">
                                                                <h4>{{i.course_id.course_title}}</h4>
                                                                <p>By {{i.course_id.inst_id.first_name }} <br>
                                                                        {{i.course_id.total_hours}} Hours
                                                                </p>
                                                        </td>
                                                        <td><br>
                                                                <p style="color:#FDAE5C;font-size:20px;font-weight: bold;"><strong>&#8377;{{i.course_id.sale_price}}</strong><br>
                                                                        <del>&#8377; {{i.course_id.course_price}}</del></p>
                                                        </td>
                                                        <td>    <br>
                                                                <a href="{% url 'myapp:remove_cart' %}?cart_id={{i.id}}" class="btn btn-danger">&times Remove</a>
                                                        </td>
                                                </tr>
                                                </a>
                                                {% endfor %}
                                        </tbody>
                                        
                                </table>
                        </div>
                        {% if not items|length == 0 %}
                        <div class="col-md-4 px-5">
                                <div class="card">
                                        <div class="card-header">
                                                <h2>CHECKOUT </h2>
                                        </div>
                                        <div class="card-body">
                                                <div style="border-bottom:2px dotted black;" class="p-2">
                                                        <script>let s=0;t=0</script>
                                                        {% for i in items %}
                                                          <h5>
                                                                  <span >Item Price</span>
                                                                  <span style="float:right">&#8377; {{i.course_id.sale_price}}</span>
                                                                <script>
                                                                        t += parseInt("{{i.course_id.course_price}}")
                                                                        s += parseInt("{{i.course_id.sale_price}}")
                                                                </script>
                                                        </h5>
                                                        {% endfor %}
                                                </div>
                                                <div style="border-bottom:2px dotted black;" class="p-2">
                                                        <h5>
                                                                <span >Offer</span>
                                                                <span style="float:right"> <script>document.write("<del>&#8377;"+t+"</del>");
                                                                let off = 100-((s/t)*100);
                                                                document.write(" ("+Math.round(off,2)+"%)")
                                                                </script></span>
                                                            
                                                      </h5> 
                                                </div>
                                                <div style="border-bottom:2px dotted black;" class="p-2">
                                                        <h5>
                                                                <span >ITEM TOTAL</span>
                                                                <span style="float:right"> <script>
                                                                document.write("&#8377;"+Math.round(s,2))
                                                                </script></span>
                                                            
                                                      </h5> 
                                                </div>
                                                <div class="py-5 text-center">
                                                        
                                                        <a href="{% url 'myapp:process_payment'%}" class="btn btn-block rounded-pill text-light" style="background:#ff5e13">PROCEED TO CHECKOUT</a>
                                                        
                                                </div>
                                        </div>
                                </div>
                        </div> 
                        {% endif %} 
                </div>
        </div>

    </section>
    {%endif %}

{% endblock %}

templates/courses.html
{% extends "base.html"%}
{% load static %}
{% block content %}
 <!-- bradcam_area_start -->
        <div class="bradcam_area  overlay2" style="background:url('/static/img.jpg');background-size:100% 100%;">
            <h3>Our Courses</h3>
        </div>
        <!-- bradcam_area_end -->

    <!-- popular_courses_start -->
    <div class="popular_courses plus_padding" id="abcd">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="course_nav">
                        <nav>
                            <ul class="nav" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                                        aria-controls="home" aria-selected="true" onclick="tab_data('None','{{i.category_title}}')">All Courses({{all|length}})</a>
                                </li>
                                {% for i in cats %}
                                <li class="nav-item">
                                    <a  class="nav-link" id="home-{{i.id}}" data-toggle="tab" href="#h{{i.id}}" role="tab"
                                        aria-controls="home" aria-selected="" onclick="tab_data('{{i.id}}','{{i.category_title}}')">{{i.category_title}}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>

        </div>
        <div class="all_courses">
            <div class="container">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            {% for i in all %}
                            <div class="col-xl-4 col-lg-4 col-md-6">
                                <div class="single_courses">
                                    <div class="thumb">
                                        <a href="{% url 'myapp:single_course' %}?cid={{i.id}}&type=normal">
                                            <img src="/media/{{i.cover_image}}" height="250" width="100%">
                                        </a>
                                    </div>
                                    <div class="courses_info">
                                        <span>{{i.course_category.course_title}}</span>
                                        <h3 style="height:50px;"><a href="{% url 'myapp:single_course' %}?cid={{i.id}}&type=normal">{{i.course_title}}</a></h3>
                                        <div class="star_prise d-flex justify-content-between">
                                            <div class="star">
                                                <i class="flaticon-mark-as-favorite-star"></i>
                                                <span>(4.5)</span>
                                            </div>
                                            <div class="prise">
                                                <span class="offer">&#8377; {{i.course_price}}</span>
                                                <span class="active_prise">
                                                    &#8377; {{i.sale_price}}
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>    
                            {% endfor %}
                        </div>
                    </div>
                    <div id="myresult"></div>
                </div>
            </div> 
        </div>
    </div>
    <!-- popular_courses_end-->
    <script>
        let cc = 1;
        function tab_data(id,cname){
            $.ajax({
                url:"{% url 'myapp:get_course_data' %}",
                type:"get",
                data:{cat_id:id},
                success:function(data){
                    let result = "";
                    
                        result += '<div  class="tab-pane fade show active"  id="h'+id+'" role="tabpanel" aria-labelledby="home-'+id+'">';                        
                   
                    result += '<div class="row">';
                    
                    for(i in data.data){
                        result += '<div class="col-xl-4 col-lg-4 col-md-6">';
                        result += '<div class="single_courses">';
                        result += '<div class="thumb">';
                        result +='<a href="#">';
                        result += '<img src="/media/'+data.data[i].cover_image+'" width="100%" height="200" alt="No Image">';
                        result += '</a>';
                        result += '</div>';
                        result += '<div class="courses_info">';
                        result += '<span>'+cname+'</span>';
                        result += '<h3 style="height:50px;"><a href="/myapp/single_course?cid='+data.data[i].id+'&type=normal">'+data.data[i].course_title+'</a></h3>';  
                        result += '<div class="star_prise d-flex justify-content-between">';  
                        result += '<div class="star">';
                        result += '<i class="flaticon-mark-as-favorite-star"></i>';
                        result += '<span>(4.5)</span>';
                        result += '</div>';
                        result += '<div class="prise">';
                        result += '<span class="offer">&#8377;'+data.data[i].course_price+' </span>';
                        result += '<span class="active_prise">&#8377;'+data.data[i].sale_price+' </span>';
                        result += '</div>';
                        result += '</div>';
                        result += '</div>';
                        result += '</div>';
                        result += '</div>';
                    }
                    result += '</div>';
                    result += '</div>';
                    $("#myTabContent").html(result);
                }
            })
        }
    </script>
{% endblock %}

templates/forgot_pass.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div style="height:100px;background:#6610f2;"></div>

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto p-5 shadow shadow-lg my-5">
            <div>
                <form method="post">
                    {% csrf_token %}
                    <h4>Get Your Password</h4> <hr>
                    <div id="msz"></div>
                    <div id="beforeotp">
                        <div class="form-group">
                            <label>Enter Username</label>
                            <input type="text" class="form-control" id="username" name="username" required>
                        </div>
                        <div class="form-group">
                            <button type="button" class="btn btn-warning" id="gp" onclick="Get_Password()">Click to Proceed</button>
                        </div>
                    </div>
                    <div class="text-center">
                        <span class="spinner spinner-grow text-warning"  id="spn" style="height:100px;width:100px;display:none;"></span>
                    </div>
                    <div id="afterotp" style="display:none;">
                        <div class="form-group">
                            <input type="number" class="form-control" placeholder="Enter OTP" required id="user_otp">
                            <input type="hidden" class="form-control" id="actual_otp">
                        </div>
                        <div class="form-group">
                            <button type="button" class="btn btn-warning" id="votp" onclick="match_otp()">Verify OTP</button>
                        </div>
                    </div>
                    <div id="changepass" style="display:none;">
                        <div class="form-group">
                            <input type="password" name="password" class="form-control" placeholder="Set Up New Password" required>
                            
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success" >CHANGE MY PASSWORD</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<script>
    function Get_Password(){
        $("#spn").show();
        let v = $("#username").val();
        $.ajax({
            url:"{% url 'myapp:verify_otp' %}",
            type:"get",
            data:{username:v},
            success:function(data){
                $("#spn").hide();
                if(data.status=="success"){
                    $("#msz").html("<p class='alert alert-info'>An OTP sent to your registered email "+data.email+"</p>")
                    $("#afterotp").slideDown(1000);     
                    $("#gp").hide();     
                    $("#actual_otp").val(data.myotp)
               
                }else if(data.status=="send_fail"){
                    $("#msz").html("<p class='alert alert-info'>Invalid Email ID (with account)/ Check Internet Connection Properly</p>")                    
                }
                else if (data.status =="failed"){
                    $("#msz").html("<p class='alert alert-danger'>No Account found with this username</p>")          
                }
            }
        })
    }

    function match_otp(){
        let aotp = $("#actual_otp").val();
        let uotp = $("#user_otp").val();
        if(aotp==uotp){
            $("#msz").html("<p class='alert alert-success'>OTP Matched !!!</p>")
            $("#afterotp").fadeOut("slow");
            $("#changepass").fadeIn();

        }else{
            $("#msz").html("<p class='alert alert-danger'>OTP does not matched !!!</p>") ;               
        }
    }
</script>

{% if status %}
<script>
    alert("{{status}}");
    window.location="/"
</script>
{% endif %}
{% endblock %}

templates/index.html
{% extends "base.html"%}
{% block content %}
{% if status %}
    <script>
        alert("{{response}}");
        window.location="/"
    </script>
{% endif %}
    <!-- slider_area_start -->
    <div class="slider_area ">
        <div class="single_slider d-flex align-items-center justify-content-center slider_bg_1">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-xl-6 col-md-6">
                        <div class="illastrator_png">
                            <img src="/static/img/banner/edu_ilastration.png">
                        </div>
                    </div>
                    <div class="col-xl-6 col-md-6">
                        <div class="slider_info">
                            <h3>Learn your <br>
                                Favorite Course <br>
                                From Online</h3>
                            <a href="{%url 'myapp:courses' %}" class="boxed_btn">Browse Our Courses</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider_area_end -->

    <!-- about_area_start -->
    <div class="about_area">
        <div class="container">
            <div class="row">
                <div class="col-xl-5 col-lg-6">
                    <div class="single_about_info">
                        <h3>Over 7000 Tutorials <br>
                            from 20 Courses</h3>
                        <p>When you enroll in a course, you'll be able to start right away or come back any time to start/continue.
                        It is lifetime access. So don't waster your time. Happy Learning!!! </p>
                        <a href="#" class="boxed_btn">Enroll a Course</a>
                    </div>
                </div>
                <div class="col-xl-6 offset-xl-1 col-lg-6">
                    <div class="about_tutorials">
                        <div class="courses">
                            <div class="inner_courses">
                                <div class="text_info">
                                    <span>20+</span>
                                    <p> Courses</p>
                                </div>
                            </div>
                        </div>
                        <div class="courses-blue">
                            <div class="inner_courses">
                                <div class="text_info">
                                    <span>7638</span>
                                    <p> Courses</p>
                                </div>

                            </div>
                        </div>
                        <div class="courses-sky">
                            <div class="inner_courses">
                                <div class="text_info">
                                    <span>230+</span>
                                    <p> Courses</p>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- about_area_end -->
<!-- our_categories_start -->
    <div class="our_latest_blog">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="section_title text-center mb-50">
                        <h3>Our Recent Categories</h3>
                    </div>
                </div>
            </div>
            <div class="row">
            {% for i in recent %}
                <div class="col-xl-4 col-md-4">
                    <div class="single_latest_blog" style="box-shadow:0px 0px 5px black;">
                        <div class="thumb">
                            <img src="/media/{{i.cover_picture}}" alt="" height="200">
                        </div>
                        <div class="content_blog p-4">
                            <div class="date">
                                <p>{{i.added_on}}</p>
                            </div>
                            <div class="blog_meta" style="height:50px;">
                                <h3><a href="{% url 'myapp:courses' %}#abcd">{{i.category_title}}</a></h3>
                            </div>
                            <p class="blog_text text-justified">
                               {{i.description|slice:100}}...
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
                <div class="col-xl-12 col-md-12 text-center">
                    
                    <a href="{% url 'myapp:about'%}#cats" class="boxed_btn">Browse More Categories</a>
                    
                </div>
            </div>
        </div>
    </div>
    <!-- our_categories_end -->
    <!-- popular_courses_start -->
    <div class="popular_courses">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="section_title text-center mb-50">
                        <h3>Popular Courses</h3>
                        <p>Your domain control panel is designed for ease-of-use and <br> allows for all aspects of your
                            domains.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-12">
                    <div class="course_nav">
                        <nav>
                            <ul class="nav" id="myTab" role="tablist">
                                {% for i in pop %}
                                <li class="nav-item">
                                    {% if i.id == 1 %}
                                    <a  class="nav-link active" id="home-{{i.id}}" data-toggle="tab" href="#h{{i.id}}" role="tab"
                                        aria-controls="home" aria-selected="" onclick="tab_data('{{i.id}}','{{i.category_title}}')">{{i.category_title}}</a>
                                    <script> 
                                        $(function(){
                                            tab_data('{{i.id}}','{{i.category_title}}') 
                                        });
                                    </script>
                                    {% else %}
                                    <a  class="nav-link" id="home-{{i.id}}" data-toggle="tab" href="#h{{i.id}}" role="tab"
                                        aria-controls="home" aria-selected="" onclick="tab_data('{{i.id}}','{{i.category_title}}')">{{i.category_title}}</a>
                                    {% endif %}
                                </li>
                                {% endfor %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>

        </div>
        <div class="all_courses">
            <div class="container">
                <div class="tab-content" id="myTabContent">
                    <!-- AJAX CODE GOES HERE -->
                </div>
            </div>
        </div>
    </div>
    <!-- popular_courses_end-->

    <!-- our_courses_start -->


    <script>
        let cc = 1;
        function tab_data(id,cname){
            $.ajax({
                url:"{% url 'myapp:get_course_data' %}",
                type:"get",
                data:{cat_id:id},
                success:function(data){
                    let result = "";
                    
                        result += '<div  class="tab-pane fade show active"  id="h'+id+'" role="tabpanel" aria-labelledby="home-'+id+'">';                        
                   
                    result += '<div class="row">';
                    
                    for(i in data.data){
                        result += '<div class="col-xl-4 col-lg-4 col-md-6">';
                        result += '<div class="single_courses">';
                        result += '<div class="thumb">';
                        result +='<a href="#">';
                        result += '<img src="/media/'+data.data[i].cover_image+'" width="100%" height="200" alt="No Image">';
                        result += '</a>';
                        result += '</div>';
                        result += '<div class="courses_info">';
                        result += '<span>'+cname+'</span>';
                        result += '<h3 style="height:50px;"><a href="/myapp/single_course?cid='+data.data[i].id+'&type=normal">'+data.data[i].course_title+'</a></h3>';  
                        result += '<div class="star_prise d-flex justify-content-between">';  
                        result += '<div class="star">';
                        result += '<i class="flaticon-mark-as-favorite-star"></i>';
                        result += '<span>(4.5)</span>';
                        result += '</div>';
                        result += '<div class="prise">';
                        result += '<span class="offer">&#8377;'+data.data[i].course_price+' </span>';
                        result += '<span class="active_prise">&#8377;'+data.data[i].sale_price+' </span>';
                        result += '</div>';
                        result += '</div>';
                        result += '</div>';
                        result += '</div>';
                        result += '</div>';
                    }
                    result += '</div>';
                    result += '</div>';
                    $("#myTabContent").html(result);
                }
            })
        }
    </script>
{% endblock %}

templates/payment_failed.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div style="height:100px;background:#6610f2;"></div>
<div class="container">
        <div class="row">
                <div class=" col-md-8 mx-auto  my-4">
                    <div class="card shadow shadow-lg text-center p-5">
                        <div class="card-body text-center" style="color:#ccc;">
                            <img src="{% static 'close.gif' %}" alt="" height="300" width="100%%">
                            <h3 class="my-3">PAYMENT FAILED!!!</h3>

                            <div class="mt-4">
                                <a href="{% url 'myapp:courses' %}" class="btn btn-block rounded-pill text-light" style="background:#ff5e13">CONTINUE SHOPPING</a>
                            </div>
                            <div class="mt-4">
                                <a href="{% url 'myapp:cart' %}" class="btn btn-success btn-block rounded-pill text-light">Back to Cart</a>
                            </div>
                        </div>

                    </div>

                </div>
        </div>
</div>
{% endblock %}

templates/process_payment.html
{% extends "base.html" %}
{% block content %}
<div style="height:100px;background:#6610f2;"></div>
<div class="container">
        <div class="row">
                <div class=" col-md-8 mx-auto  my-4">
                    <div class="card shadow shadow-lg text-center p-5">
                        <div class="card-body">
                            <h2>MAKE PAYMENT WITH PAYPAL</h2>
                            {{form.render}}

                            <div class="mt-4">
                                <a href="{% url 'myapp:cart' %}" class="btn btn-block rounded-pill text-light" style="background:#ff5e13">Back to Cart</a>
                            </div>
                        </div>

                    </div>

                </div>
        </div>
</div>
{% endblock %}