myapp/urls.py
from django.urls import path
from myapp import views

app_name="myapp"

urlpatterns = [
    path('courses', views.courses, name="courses"),
    path('about', views.about, name="about"),
    path('contact', views.contact, name="contact"),
    path('signup', views.signup, name="signup"),
    path('check_user', views.check_user, name="check_user"),
    path('user_login', views.user_login, name="user_login"),
    path('dashboard', views.dashboard, name="instructor_dashboard"),
    path('instructor_profile', views.instructor_profile, name="instructor_profile"),
    path('us_logout', views.us_logout, name="us_logout"),
    path('inst_add_course', views.inst_add_course, name="inst_add_course"),
    path('instructor_courses', views.instructor_courses, name="instructor_courses"),
    path('edit_course', views.edit_course, name="edit_course"),
    path('delete_topic', views.delete_topic, name="delete_topic"),
    path('add_inst_experience', views.add_inst_experience, name="add_inst_experience"),
    path("change_pass",views.change_pass,name="change_pass"),
    path("single_course",views.single_course,name="single_course"),
    path("get_course_data",views.get_course_data,name="get_course_data"),
    path("cart",views.add_cart,name="cart"),
    path("process_payment",views.process_payment,name="process_payment"),
    path("student_orders",views.student_orders,name="student_orders"),
    path("pending_orders",views.pending_orders,name="pending_orders"),
    path("remove_cart",views.remove_cart,name="remove_cart"),
    path("forgot_pass",views.forgot_pass,name="forgot_pass"),
    path("verify_otp",views.verify_otp,name="verify_otp"),
    path("student_single_course",views.student_single_course,name="student_single_course"),
    path("my_students",views.my_students,name="my_students"),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path("myapp/",include("myapp.urls")),

    path('paypal/', include('paypal.standard.ipn.urls')),

    path('ps/',views.p_success,name='ps'),
    path('pf/',views.p_fail, name='pf' ),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/dashboard/changepass.html
{% extends "dashboard/dashboard_base.html" %}
{% load static %}
{% block head %}
<style>

 </style>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 bg-white mx-auto">
            <form action="" method="post">
                {% csrf_token %}
                <h2>Get Your Password</h2><hr>
                {% if msz %}
                    <div class="alert {{status}}">{{msz}}</div>
                {% endif %}
                <div class="form-group">
                    <label>Current Password</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fas fa-eye" id="pasicon" style="font-size: 15px;" onclick="abcd()"></i>
                            </span>
                        </div> 
                        <input type="password" placeholder="Current Password"
                        class="form-control" name="old" id="old">
                    </div>
                </div>
                <div class="form-group">
                    <label> New Password</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fas fa-key" style="font-size: 15px;"></i>
                            </span>
                        </div>
                    
                    <input type="password" placeholder="New Password"
                    class="form-control " name="new" id="new" onkeyup="match_pass()">
                    </div>
                </div>
                <div class="form-group">
                    <label>Confirm Password</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fas fa-key" style="font-size: 15px;"></i>
                            </span>
                        </div>
                    
                    <input type="password" placeholder="confirm Password"
                    class="form-control "name="anew" id="pnew" onkeyup="match_pass()">
                    </div>
                </div>
           <button id="submit" class="btn btn-success" type="submit">Reset Password</button>
            </form>
        </div>
    </div>
</div>
    <script>
        function match_pass(){
            let p = $("#new").val();
            let cp = $("#pnew").val();
            
            if(p==cp){
                $("#new").css("border","1px solid green");
                $("#pnew").css("border","1px solid green");
                $("#submit").removeAttr("disabled")
            }else{
                $("#new").css("border","1px solid red");
                $("#pnew").css("border","1px solid red");
                $("#submit").attr("disabled","disabled")
            }
        }

     
    function abcd(){
        let a = $("#old").attr("type");
        if(a=="password"){
            $("#old").attr("type","text")
            $("#pasicon").removeClass("fas fa-eye").addClass("fas fa-eye-slash");
        }else{
            $("#old").attr("type","password")
            $("#pasicon").removeClass("fas fa-eye-slash").addClass("fas fa-eye");
        }
    }
            
    </script>
{% endblock %}

templates/dashboard/dashboard_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png'%}">
  <link rel="icon" type="image/png" href="{% static 'img/logo1.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    PIONEER PYTHON | TEACHER DASHBOARD
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  <!-- CSS Files -->
  <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/css/paper-dashboard.css' %}?v=2.0.1" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
{% block head %} {% endblock %}

</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="white" data-active-color="danger">
      <div class="logo">
        <a href="" class="simple-text logo-mini">
          <div class="logo-image-small">
              {% if inst.profile_picture %}
                <img src="/media/{{inst.profile_picture}}" alt="..." class="rounded-circle">
              {% else %}
                <img src="/static/noimg.png" alt="..."  class="rounded-circle">
              {% endif %}
          </div>
          <!-- <p>CT</p> -->
        </a>
        <a href="https://www.creative-tim.com" class="simple-text logo-normal">
          {{user.first_name}}
         
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li>
            <a href="{% url 'myapp:instructor_dashboard' %}">
              <i class="nc-icon nc-bank"></i>
              <p>Dashboard</p>
            </a>
          </li> 
          {% if not user.is_staff %}
          <li class="nav-item btn-rotate ">
            <a class="nav-link" href="{% url 'myapp:cart' %}" id="navbarDropdownMenuLink" >
              <i class="nc-icon nc-cart-simple"></i>
              <p>My Cart</p>
            </a>
          </li>
          <li>
            <a href="{% url 'myapp:student_orders' %}">
              <i class="nc-icon nc-briefcase-24"></i>
              <p>My Orders</p>
            </a>
          </li>
          <li>
            <a href="{% url 'myapp:pending_orders' %}">
              <i class="nc-icon nc-briefcase-24"></i>
              <p>Pending Orders</p>
            </a>
          </li>
          {% endif%}
          {% if user.is_staff %}
          <li>
            <a href="{% url 'myapp:instructor_courses' %}">
              <i class="nc-icon nc-briefcase-24"></i>
              <p>My Courses</p>
            </a>
          </li>
          <li>
            <a href="{% url 'myapp:inst_add_course' %}">
              <i class="nc-icon nc-hat-3"></i>
              <p>Add Course</p>
            </a>
          </li>
          <li>
            <a href="{% url 'myapp:add_inst_experience' %}">
              <i class="nc-icon nc-watch-time"></i>
              <p>Add Experience</p>
            </a>
          </li>
          <li>
            <a href="{% url 'myapp:my_students' %}">
              <i class="nc-icon nc-circle-10"></i>
              <p>My Students</p>
            </a>
          </li>
          {% endif %}
          <li>
            <a href="{% url 'myapp:instructor_profile' %}">
              <i class="nc-icon nc-single-02"></i>
              <p>Edit Profile</p>
            </a>
          </li>
          <li>
            <a href="{% url 'myapp:change_pass' %}">
              <i class="nc-icon nc-key-25"></i>
              <p>Change Password</p>
            </a>
          </li>
          <li class="active-pro">
            <a href="{% url 'myapp:us_logout' %}">
              <i class="nc-icon nc-button-power"></i>
              <p>Logout</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
        <div class="container-fluid bg-light">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a href="{% url 'index' %}" class="navbar-brand">
              Home &gt;
            </a>
            {% if user.is_staff %}
            <a class="navbar-brand" href="javascript:;">Instructor Dashboard</a>
            {% else %}
            <a class="navbar-brand" href="javascript:;">Student Dashboard</a>
            {% endif %}
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
           {% if user.is_staff %}
            <form method="post" action="{% url 'myapp:instructor_courses' %}">
              {% csrf_token %}
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search..." name="search">
                <div class="input-group-append">
                  <div class="input-group-text">
                   <button style="border:none;" type="submit"> <i class="nc-icon nc-zoom-split"></i></button>
                  </div>
                </div>
              </div>
            </form>
            {% endif %}
            <ul class="navbar-nav d-lg-none d-md-block">
              <li class="nav-item">
                <a class="nav-link btn-magnify" href="{% url 'myapp:instructor_dashboard' %}">
                  <i class="nc-icon nc-layout-11"></i>
                  <p>
                   Dashboard
                  </p>
                </a>
              </li>
              {% if not user.is_staff %}
          <li class="nav-item btn-rotate ">
            <a class="nav-link" href="{% url 'myapp:cart' %}" id="navbarDropdownMenuLink" >
              <i class="nc-icon nc-cart-simple"></i>
              <p>My Cart</p>
            </a>
          </li>
          <li class="nav-item btn-rotate ">
            <a href="{% url 'myapp:student_orders' %}" class="nav-link">
              <i class="nc-icon nc-briefcase-24"></i>
              <p>My Orders</p>
            </a>
          </li>
          <li class="nav-item btn-rotate ">
            <a href="{% url 'myapp:pending_orders' %}" class="nav-link">
              <i class="nc-icon nc-briefcase-24"></i>
              <p>Pending Orders</p>
            </a>
          </li>
          {% endif%}
          {% if user.is_staff %}
              <li class="nav-item btn-rotate ">
                <a class="nav-link" href="{% url 'myapp:inst_add_course' %}" id="navbarDropdownMenuLink" >
                  <i class="nc-icon nc-hat-3"></i>
                  <p>Add Course</p>
                </a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link btn-rotate" href="{% url 'myapp:instructor_courses' %}">
                    <i class="nc-icon nc-briefcase-24"></i>
                    <p>My Courses</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'myapp:my_students' %}" class="nav-link">
                  <i class="nc-icon nc-circle-10"></i>
                  <p>My Students</p>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link btn-rotate" href="{% url 'myapp:add_inst_experience' %}">
                  <i class="nc-icon nc-watch-time"></i>
                  <p>Add Experience</p>
                </a>
              </li>
              {% endif %}
              
              <li class="nav-item">
                <a href="{% url 'myapp:instructor_profile' %}" class="nav-link">
                  <i class="nc-icon nc-single-02"></i>
                  <p>Edit Profile</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'myapp:change_pass' %}" class="nav-link">
                  <i class="nc-icon nc-key-25"></i>
                  <p>Change Password</p>
                </a>
              </li>
              
              <li class="active-pro nav-item">
                <a href="{% url 'myapp:us_logout' %}" class="nav-link">
                  <i class="nc-icon nc-button-power"></i>
                  <p>Logout</p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="row">
          {% block content %}

          {% endblock %}          
        </div>
      </div>
      <footer class="footer footer-black  footer-white ">
        <div class="container-fluid">
          <div class="row">
            <nav class="footer-nav">
              <ul>
                <li><a href="" target="_blank">PIONEER PYTHON TEAM</a></li>
              </ul>
            </nav>
            <div class="credits ml-auto">
              <span class="copyright">
                © <script>
                  document.write(new Date().getFullYear())
                </script>, made with <i class="fa fa-heart heart"></i> by PIONEER PYTHON TEAM
              </span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="{% static 'assets/js/core/jquery.min.js' %}"></script>
  <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chart JS -->
  <script src="{% static 'assets/js/plugins/chartjs.min.js' %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'assets/js/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'assets/js/paper-dashboard.min.js' %}?v=2.0.1" type="text/javascript"></script><!-- Paper Dashboard DEMO methods, don't include it in your project! -->
  <script src="{% static 'assets/demo/demo.js' %}"></script>
  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/assets-for-demo/js/demo.js
      demo.initChartsPages();
    });
  </script>
</body>

</html>

templates/dashboard/edit_course.html
{% extends "dashboard/dashboard_base.html" %}
{% load bootstrap4 %}
{% block head %}
<script src="/static/jquery.js"></script>
  <style>
    .nc-icon,.ic{
      font-size:20px;
    }
    input{
      height:35px !important;
    }
    #watch{
      animation: myani 2s infinite linear;display:none;
    }
    .ch{
      background:#ef8157 !important;
    }
    .ch .card-link{
      color:white;
    }
    @keyframes myani{
      from{transform:rotate(0deg)}
      to{transform:rotate(360deg)}
    }
  </style>
{% endblock %}
{% block content %}
<div class="container-fluid">
  <div class="row">
    <!-- EDIT COURSE -->
    <div class="col-md-12">
      <div class="card demo-icons">
        <div class="card-header text-center">
          <h5 class="card-title">Edit Course</h5>
        </div>
        <div class="card-body bg-light">
          <div class="container">
            <div class="row">
              <!-- EDIT FIELDS LEFT SIDE -->
              <div class="col-md-8">
                <div class="row">
                  <div class="col-md-6">
                    <img src="/media/{{course.cover_image}}" height="200" width="100%">
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Course Title</label>
                      <input type="text" class="form-control" placeholder="Course Title" value="{{course.course_title}}" id="title">
                    </div>
                    <div class="form-group">                  
                      <label>Course Category</label>
                      <input type="text" class="form-control" placeholder="Course Category" value="{{course.course_category.category_title}}" disabled>
                    </div>
                    <div class="form-group">                  
                      <div class="row">
                        <div class="col-md-6">
                          <label>Course Price (&#8377;)</label>
                          <input type="number" class="form-control" placeholder="Course Price" value="{{course.course_price}}" id="price">    
                        </div>
                        <div class="col-md-6">
                          <label>Discount Price (&#8377;)</label>
                          <input type="number" class="form-control" placeholder="Course Price" value="{{course.sale_price}}" id="sprice">    
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <textarea name="description" rows="20" class="form-control" id="description">{{course.description}}</textarea>
                  </div>
                  <div class="col-md-12">
                    <button class="btn ch" onclick="save_changes()"> <i class="nc-icon nc-watch-time" id="watch"></i> Save Changes</button>
                  </div>
                </div>
              </div>

              <!-- ADD TOPIC -->
              <div class="col-md-4">
                <div class="card">
                  <div class="card-body">
                    {% if status %}
                      <p class="alert alert-info">{{status}}</p>
                    {% endif %}
                    <form action="" method="post" enctype="multipart/form-data">
                      {% csrf_token%}
                      <div class="form-group"> 
                        <label for="">Topic Name</label>
                        <input type="text" class="form-control" placeholder="Topic Name" id="topic" name="topic">
                        <input type="hidden" class="form-control" value="{{course.id}}"name="cid">
                      </div>
                      <div class="form-group"> 
                        <label for="">Content</label>
                        <textarea name="content" id="content" class="form-control" placeholder="Content"></textarea>
                      </div>
                      <div class="form-group"> 
                        <label for="">Click to Upload Video</label>
                        <input type="file" name="video" class="form-control">
                      </div>
                      <button type="submit" class="btn btn-success btn-block">Add Topic</button>
                    </form>
                  </div>
                </div>
              </div>
              <hr>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- All Topics -->
    <div class="col-md-12">
      <div class="card demo-icons">
        <div class="card-header text-center">
          <h5 class="card-title">All topics ({{topics|length}}) </h5>
        </div>
        <div class="card-body">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <div id="accordion">
                {% for i in topics %}
                  <div class="card">
                    <div class="card-header ch">
                      <a class="float-left card-link {% if i.id == topics|length %} collapsed {% endif %}" data-toggle="collapse" href="#collapse{{i.id}}">
                        {{i.topic_name}}
                      </a>
                      <a onclick="delTopic('{{i.id}}','{{i.topic_name}}')" class="float-right card-link"><i class="fa fa-trash ic"></i></a>
                    </div>
                    <div id="collapse{{i.id}}" class="collapse {% if   i.id == topics|length %} show {% endif %} " data-parent="#accordion">
                      <div class="card-body">
                        {{i.content}}
                        <video src="/media/{{i.file}}" controls  width="100%">
                          <source src="/media/{{i.file}}">
                        </video>

                        <em class="float-right">Upload On: {{i.added_on}}</em>
                      </div>
                    </div>
                  </div>
                {% endfor %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  function save_changes(){
    let tt = document.getElementById("title").value;
    let pr = document.getElementById("price").value;
    let sp = document.getElementById("sprice").value;
    let des = document.getElementById("description").value;
    $("#watch").show();
    $.ajax({
      url:"{% url 'myapp:edit_course' %}",
      type:"get",
      data:{id:'{{course.id}}',title:tt,price:pr,sp:sp,des:des},
      success:function(data){
        alert(data);
        $("#watch").hide();
      }
    })
  }
</script>
<script>
  function delTopic(id,topic){
    con = confirm("Are you sure want to delete "+topic+"?\nClick OK to Delete");
    if(con==true){
      $.ajax({
        url:"{% url 'myapp:delete_topic' %}",
        type:"get",
        data:{topic_id:id},
        success:function(data){
          alert(topic+data);
        }
      })
    }else{

    }
  }
</script>
{% endblock %}

templates/dashboard/instructor_courses.html
{% extends "dashboard/dashboard_base.html" %}
{% load bootstrap4 %}

{% block head %}

<script src="/static/jquery.js"></script>
<style>
    .ic{
        font-size: 25px;
    }
</style>

{% endblock %}
{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card demo-icons">
        <div class="card-header text-center">
          <h5 class="card-title">My Courses ({{courses|length}})</h5>
        </div>
        <div class="card-body bg-light">
          <div class="container">
            <div class="row">
              <div class="col-md-12 mx-auto">
                <table class="table table-sm table-hover">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Course</th>
                            <th>Course Title</th>
                            <th>Category</th>
                            <th>Date Published</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in courses %}
                        <a href="/cid={{i.id}}">
                        <tr>
                            <td>{{i.id}}</td>
                            <td><img src="/media/{{i.cover_image}}" height="50" width="100"></td>
                            <td>{{i.course_title}}</td>
                            <td>{{i.course_category.category_title}}</td>
                            <td>{{i.added_on}}</td>
                            <td>
                                <div class="row">
                                    <div class="col-md-3">
                                        <a href="{% url 'myapp:single_course' %}?cid={{i.id}}"><i class="fa fa-eye ic"></i></a>
                                    </div>
                                    <div class="col-md-3">
                                        <a href="{% url 'myapp:edit_course' %}?cid={{i.id}}"><i class="fa fa-edit ic"></i></a>
                                    </div>
                                    <div class="col-md-3">
                                        <a onclick="del_course('{{i.id}}','{{i.course_title}}')"><i class="fa fa-trash text-danger ic"></i></a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        </a>
                        {% endfor %}
                    </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  function del_course(id,topic){
    con = confirm("Are you sure want to delete "+topic+"?\nClick OK to Delete");
    if(con==true){
      $.ajax({
        url:"{% url 'myapp:delete_topic' %}",
        type:"get",
        data:{course_id:id},
        success:function(data){
          alert(topic+data);
        }
      })
    }else{

    }
  }
</script>
{% endblock %}

templates/dashboard/my_students.html
{% extends "dashboard/dashboard_base.html" %}
{% load bootstrap4 %}

{% block head %}

<script src="/static/jquery.js"></script>

{% endblock %}
{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card demo-icons">
        <div class="card-header text-center">
          <h5 class="card-title">My Students ({{students|length}})</h5>
        </div>
        <div class="card-body bg-light">
          <div class="container">
            <div class="row">
              {% for i in students %}
                <div class="col-md-4">
                    <div class="p-4 bg-white">
                      {% if i.image %}
                        <img src="/media/{{i.image}}" alt="..." class="img-rounded" height="250" width="100%">
                      {% else %}
                        <img src="/static/noimg.png" alt="..."  class="rounded-circle" height="250" width="100%">
                      {% endif %}
                      <h4>{{i.name }}</h4>
                      <p><i class="fas fa-envelope"></i> {{i.email}}</p>
                      {% if i.qualification %}
                        {{i.qualification}} ({{i.position}})
                      {% endif %}
                    </div>  
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>

</script>
{% endblock %}

templates/dashboard/student_orders.html
{% extends "dashboard/dashboard_base.html" %}
{% load static %}
{% block head %}
<style>
  
</style>
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card demo-icons">
          <div class="card-header text-center">
            <h5 class="card-title">My Orders ({{courses|length}})</h5>
          </div>
          <div class="card-body">
            <div class="container">
              <div class="row hello">
               
                {% for i in courses %}
                <div class="col-xl-12 col-lg-12 col-md-12 mb-5">
                    <div class="single_courses">
                      <div class="row">
                        <div class="col-md-5">
                          <div class="thumb">
                            <a href="{% url 'myapp:single_course' %}?cid={{i.id}}&type=normal">
                                <img src="/media/{{i.cover_image}}" height="200" width="100%">
                            </a>
                          </div>
                        </div>
                        <div class="col-md-7">
                          <div class="courses_info">
                            <span>{{i.course_category.course_title}}</span>
                            <h3 style="height:50px;"><a href="{% url 'myapp:student_single_course' %}?cid={{i.id}}"></a>{{i.course_title}}</a></h3>
                            <div class="star_prise d-flex justify-content-between">
                            
                                <div class="prise" style="font-size:22px;">
                                    <span class="offer"><del>&#8377; {{i.course_price}}</del></span>
                                    <span class="active_prise">
                                        &#8377; {{i.sale_price}}
                                    </span>
                                </div>
                            </div>
                            <div>
                              <a href="{% url 'myapp:student_single_course' %}?cid={{i.id}}" class="btn btn-success rounded-pill">Read Course</a>
                            </div>
                        </div>
                        </div>
                      </div>
                        
                    </div>
                </div>    
                {% endfor %}
            
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}